version: '3.8'

services:
  # Go    
  producer:
    container_name: producer
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/go/src
    ports:
      - '6050:6030'
    command: tail -F anything      

  # PostgreSQL container
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: public
    ports:
      - '5432:5432'